POST http://localhost:3001/api/blogs
Content-Type: application/json

    {
        "title": "Toinen blogi posti",
        "author": "L7034",
        "url": "Skippyprogressive",
        "likes": 25
    }   
